version: "3"
services:
  client:
    build: client
    container_name: client
    env_file:
      - ./.env
    links:
      - server
    ports:
      - "127.0.0.1:5000:4000"
  server:
    build: server
    container_name: server
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:5001:4001"
    restart: always
